import type { EvidenceReference } from "./measurement-types.ts";
import { DATASET_SNAPSHOT } from "../data/dataset-snapshot.ts";

const checked = DATASET_SNAPSHOT.researchCutoff;
const evidenceId = (url: string) => `source-${url.replace(/^https?:\/\//, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase()}`;
const ref = (title: string, organization: string, url: string, sourceType: EvidenceReference["sourceType"], supports: string, publicationDate?: string): EvidenceReference => ({ id: evidenceId(url), title, organization, url, sourceType, supports, publicationDate, accessedDate: checked });

/** Production evidence ledger for the August 16, 2026 observation snapshot. */
export const MEASUREMENT_EVIDENCE: Record<string, EvidenceReference[]> = {
  "robotics-1": [ref("Clarification regarding Unitree's 2025 sales data", "Unitree", "https://shop.unitree.com/zh-au/blogs/news/clarification-regarding-unitrees-2025-sales-data", "official", "Unitree reports more than 5,500 pure humanoid robots sold and delivered to end customers in 2025; the separate 6,500 figure is production and is not counted.")],
  "lev-1": [ref("World Population Prospects 2024", "United Nations, Department of Economic and Social Affairs, Population Division", "https://population.un.org/wpp/Download/Standard/MostUsed/", "official", "The 2026 world estimate for life expectancy at birth, both sexes combined, is 73.768 years.")],
  "lev-3": [ref("Oldest person living", "Guinness World Records", "https://www.guinnessworldrecords.com/world-records/67479-oldest-person-living", "official", "Ethel Caterham, born 21 August 1909, remained the verified oldest living person and was 116 years, 360 days old at the cutoff.")],
  "lev-4": [ref("World Supercentenarian Rankings List", "Gerontology Research Group", "https://www.grg-supercentenarians.org/world-supercentenarian-rankings-list/", "official", "The 203 living validated entries at the cutoff are an exact GRG list count, not a census estimate of the world's true living supercentenarian population.")],
  "space-1": [ref("Most people in space at once", "Guinness World Records", "https://www.guinnessworldrecords.com/world-records/72199-most-people-in-space-at-once", "official", "Documents the record of 19 people simultaneously above the 100 km boundary.")],
  "space-moon-pop": [ref("Apollo 17 mission details", "NASA", "https://www.nasa.gov/missions/apollo/apollo-17-mission-details/", "official", "Documents the final crewed lunar-surface mission and two people simultaneously on the Moon.")],
  "space-mars-pop": [ref("Humans to Mars", "NASA", "https://www.nasa.gov/humans-in-space/humans-to-mars/", "official", "NASA describes human Mars exploration as future work; the complete human-spaceflight record contains no Mars landing.")],
  "space-2": [ref("Buran characteristics", "Buran programme archive", "https://buran.fr/en/bourane-buran/bourane-carac.php", "technical", "Documents Buran's 79.4-tonne flown orbital mass on 15 November 1988.")],
  "qc-gate-model-physical-qubits": [ref("AC1000", "Atom Computing", "https://atom-computing.com/ac1000/", "technical", "Documents a universal gate-model neutral-atom system with more than 1,200 physical qubits.")],
  "qc-system-two-qubit-fidelity": [ref("Helios", "Quantinuum", "https://www.quantinuum.com/products-solutions/quantinuum-systems/helios", "technical", "Reports 99.921% average two-qubit gate fidelity for Helios.")],
  "qc-3": [ref("System Model H2", "Quantinuum", "https://www.quantinuum.com/products-solutions/quantinuum-systems/system-model-h2", "technical", "Documents the H2 Quantum Volume record of 33,554,432.")],
  "qc-4": [ref("IBM Quantum system performance", "IBM Quantum", "https://quantum.cloud.ibm.com/services/resources", "technical", "IBM's published system metrics report approximately 340K hardware-aware CLOPS_h for a Heron system.")],
  "lev-2": [ref("World Population Prospects 2024", "United Nations, Department of Economic and Social Affairs, Population Division", "https://population.un.org/wpp/Download/Standard/MostUsed/", "official", "The WPP 2024 snapshot gives Monaco's 2026 life expectancy at birth as 86.734 years; FPB displays 86.7.")],
  "superconductor-je-20k-20t": [ref("MIRAI second-generation HTS tape", "Faraday Factory Japan", "https://www.csj.or.jp/caj/supporting_member/index.html?id=FaradayFactoryJapan", "technical", "Commercial MIRAI tape material specifies engineering current density Je of at least 1,200 A/mm² at 20 K and 20 T; this is a documented floor, not an exhaustive manufacturer census.")],
  "superconductor-3": [ref("Prototype miniature superconducting magnet", "National High Magnetic Field Laboratory", "https://nationalmaglab.org/news-events/news/a-prototype-miniature-superconducting-magnet", "official", "Documents the 48.7 T non-destructive superconducting magnet result.")],
  "superconductor-commercial-piece-length": [ref("2G HTS tape", "Shanghai Superconductor Technology", "https://www.shsctec.com/en/products/tape/", "technical", "Commercial specifications offer continuous tape lengths up to 1.0 km.")],
  "self-driving-car-2": [ref("Autonomous Vehicle Deployment Program", "California Public Utilities Commission", "https://www.cpuc.ca.gov/regulatory-services/licensing/transportation-licensing-and-analysis-branch/autonomous-vehicle-programs", "official", "Ordinary paid driverless passenger service is authorized in parts of the United States."), ref("Beijing opens autonomous driving service area", "Beijing Municipal Government", "https://english.beijing.gov.cn/latest/news/202503/t20250304_4023444.html", "official", "China permits public autonomous-driving services in a defined city area.")],
  "bci-1": [
    ref("Two years of Telepathy", "Neuralink", "https://neuralink.com/updates/two-years-of-telepathy/", "official", "Reports 21 Telepathy recipients by the cutoff."),
    ref("NEO clinical progress", "Chinese Academy of Sciences", "https://english.casad.cas.cn/newsroom/ma/202607/t20260706_1176268.html", "official", "Supports the completed NEO pre-market cohort."),
    ref("Synchron update", "University of Melbourne", "https://medicine.unimelb.edu.au/school-structure/radiology/news-and-events/news/Synchrons-update", "official", "Supports historical Stentrode implanted cohorts."),
    ref("ARC-BCI", "ONWARD Medical", "https://www.onwd.com/brain-computer-interface/", "official", "Supports five WIMAGINE ARC-BCI recipients."),
    ref("Third Brain Interchange patient", "CorTec", "https://cortec-neuro.com/brain-interchange-fda-tap-third-patient/", "official", "Supports three Brain Interchange recipients."),
    ref("First long-term Connexus implantation", "Paradromics", "https://paradromics.com/news/paradromics-completes-first-human-brain-computer-interface-bci-implantation/", "official", "Supports one long-term Connect-One recipient."),
    ref("Three-full system", "NeuroXess", "https://www.neuroxess.com/news/kejixiangshan/", "official", "Supports two qualifying NeuroXess recipients."),
  ],
  "bci-3": [ref("China approves invasive BCI medical device", "Xinhua", "https://english.news.cn/20260313/0d8d04954ef845c4b6de502c725c832f/c.html", "official", "Reports NMPA approval of NEO on 13 March 2026 as the first market approval of an invasive implantable BCI medical device."), ref("First post-market NEO implantation", "Shanghai municipal government", "https://segg.sh.gov.cn/pdfpt/gzdt/20260717/71d7bd2de0cf445a87ea002f26f4770d.html", "official", "Documents the first ordinary post-market prescription and implantation in Shanghai on 13 July 2026.")],
  "mind-upload-1": [ref("FlyWire Codex", "FlyWire", "https://codex.flywire.ai/about", "technical", "MCNS v0.9 reports 166,694 neurons and 6,239,112 connections for the male adult fly CNS.")],
  "vr-commercial-ppd": [ref("57 PPD optical engine", "Pimax", "https://pimax.com/blogs/blogs/first-look-at-pimax-crystal-super-s-new-57-ppd-optical-engine", "technical", "Documents the shipping 57-PPD optical configuration.")],
  "vr-shared-world-concurrency": [ref("Instances", "VRChat", "https://wiki.vrchat.com/wiki/Special%3AMyLanguage/Instances/en", "technical", "Documents configurable capacity 80 plus normal reserved creator and author access, an effective 82; staff manual overrides are excluded.")],
  "fusion-3": [ref("ITER FAQs", "ITER Organization", "https://www.iter.org/faqs?untranslated=1", "official", "States that Q=1 has never been achieved in a magnetic-confinement fusion device and identifies JET's record near Q=0.67.")],
  "bci-2": [ref("Clinical trials database", "U.S. National Library of Medicine", "https://clinicaltrials.gov/", "official", "Country and trial records were checked against formal registered human studies; the public cross-country total remains a lower bound.")],
  "cultured-meat-3": [ref("Cell-cultivated products for animal feed", "UK Food Standards Agency", "https://www.food.gov.uk/news-alerts/news/cell-cultivated-products-approved-for-use-in-animal-feed", "official", "The United Kingdom authorized a cultivated product for use in pet food.")],
  "cultured-meat-2": [
    ref("Safety assessment of cultivated chicken", "Singapore Food Agency", "https://www.sfa.gov.sg/food-information/risk-at-a-glance/safety-of-alternative-protein", "official", "Singapore permits an assessed cultivated-meat product for human consumption."),
    ref("Human Food Made with Cultured Animal Cells", "U.S. Food and Drug Administration", "https://www.fda.gov/food/food-ingredients-packaging/human-food-made-cultured-animal-cells", "official", "The United States completed federal pre-market consultations for cultivated chicken products."),
    ref("Approval report A1269", "Food Standards Australia New Zealand", "https://www.foodstandards.gov.au/food-standards-code/applications/A1269-Cultured-Quail", "official", "The Australia/New Zealand joint food code authorized cultivated quail, establishing separate operative permission in both countries."),
    ref("World's first regulatory approval for cultivated beef", "Israel Ministry of Health", "https://www.gov.il/en/pages/press_17012024", "official", "Israel authorized a cultivated-beef product for human consumption."),
  ],
};
