import type { NorthStarDefinition } from "./measurement-types.ts";

const make = (id: string, title: string, question: string, unit: string, methodology: string, temporalType: "current" | "record" = "record"): NorthStarDefinition => ({
  id, title, question, construct: methodology, variable: title, unit, methodology, temporalType,
  researchCutoff: "2026-08-16", definitionVersion: "1.0.0", effectiveFrom: "2026-08-16",
  evidenceRequirements: ["Every plotted point MUST retain its source, observation year, retrieval date, value, and calculation note in the series module."],
  knownLimitations: ["Historical series may mix source vintages; missing point-level provenance is a disclosed legacy limitation and MUST NOT be silently invented."],
  series: { sourceModule: `src/components/${id}-graph-data.ts`, frequency: "annual", provenance: "Point provenance is retained in the named graph-data module; legacy points without complete citations remain explicitly incomplete." },
});

/** Canonical identity for the 12 contextual, non-scoring graph series. */
export const NORTH_STARS: Record<string, NorthStarDefinition> = {
  ai: make("ai", "10 PFLOP/s Dense FP32 Hardware Cost", "What did commercially available hardware capable of 10^16 dense FP32 FLOP/s cost in each year?", "2026 USD", "Uses purchase prices and sustained dense-FP32 specifications available in the stated year. The 10^16 FLOP/s target is a project raw-compute reference, not established equivalence with human cognition."),
  robotics: make("robotics", "Taxels (Tactile Pixels) per 5-Fingered Robotic Hand", "What is the record number of independently sensed tactile pixels on a five-fingered robotic hand?", "taxels", "Counts independently sensed tactile locations on a complete five-fingered robotic hand; component skins, projections, and announced designs are excluded."),
  "self-driving-car": make("self-driving-car", "Global Share of Distance Traveled by L4/L5 Self-Driving Vehicles", "What share of worldwide road-vehicle distance is traveled under SAE Level 4 or Level 5 automated driving?", "% of vehicle-distance", "Numerator is distance actually driven under SAE L4/L5 control; denominator is compatible worldwide road-vehicle distance in the same year. Testing and lower automation levels are excluded.", "current"),
  lev: make("lev", "Annual Increase in Lifespan & Healthspan", "How much did measured human lifespan and healthspan increase during each annual observation?", "years gained per year", "Keeps lifespan and healthspan as separate annual changes under the definitions attached to each series point; it does not treat maximum age as population life expectancy.", "current"),
  "space-exploration": make("space-exploration", "Maximum Commercial Efficiency to LEO", "What is the best achieved commercial launch cost per kilogram delivered to qualifying LEO?", "2026 USD/kg to LEO", "Uses achieved commercial mission price and actual delivered mass, inflation-adjusted to 2026 USD; advertised future prices and theoretical launcher capacity are excluded."),
  "quantum-computing": make("quantum-computing", "Maximum Encoded Logical Qubits Used in a Programmable Quantum Computation", "What is the record number of encoded logical qubits used together in an executed programmable quantum computation?", "logical qubits", "Counts encoded logical qubits actually used in a programmable computation, not physical qubits, memory-only demonstrations, or roadmap targets."),
  superconductor: make("superconductor", "Highest Critical Temperature (Tc) at Ambient Pressure", "What is the highest independently credible superconducting critical temperature at ambient pressure?", "kelvin", "Uses reproduced or strongly supported ambient-pressure superconducting transitions; high-pressure and retracted claims are excluded."),
  bci: make("bci", "Stevenson’s Law: BCI Information-Transfer Rate", "What is the best demonstrated usable information-transfer rate of a qualifying brain–computer interface?", "bits/s", "Uses task-level neural information transfer with the interface and assistance boundary documented; chronic implanted and non-invasive series are not silently treated as equivalent."),
  "mind-upload": make("mind-upload", "Neurons Simulated", "What is the record number of biologically based neurons simulated together in a published neural simulation?", "neurons", "Counts neurons in an executed biologically based simulation, not connectome nodes alone, generic artificial-network units, or a claim of consciousness or personal continuity."),
  vr: make("vr", "Simultaneous Neural Stimulation Channels", "What is the record number of independently controlled neural stimulation channels demonstrated simultaneously for immersive sensory interfacing?", "channels", "Counts simultaneously controlled neural/CNS stimulation channels in a documented demonstration; headset pixels, peripheral haptics, and electrode totals without independent control are excluded."),
  "cultured-meat": make("cultured-meat", "Maximum Viable Structured Tissue Thickness", "What is the greatest demonstrated thickness of viable structured cultivated animal tissue?", "millimetres", "Uses achieved viable structured tissue grown outside a living animal, with viability across the claimed thickness; announced scale and unstructured cell mass are excluded."),
  "nuclear-fusion": make("nuclear-fusion", "Lawson Criterion", "What is the highest achieved fusion triple product under a documented experimental boundary?", "keV·s/m³", "Uses achieved temperature × density × confinement time with device and fuel boundary documented; scientific Q, target gain, and net electricity remain distinct metrics."),
};
