import type { ResearchAuditRecord, ResultStatus } from "./measurement-types.ts";
import { DATASET_SNAPSHOT } from "../data/dataset-snapshot.ts";

const cutoff=DATASET_SNAPSHOT.researchCutoff;
const descriptions: Record<string,{status:ResultStatus;scope:string;candidates:string[];families:string[];conclusion:string;limitations:string;complete?:"exhaustive"|"systematic-nonexhaustive"|"targeted"}> = {
 "ai-millennium-problems":{status:"no-verified-result",scope:"All seven Clay Millennium Problems and Clay's recognition rules.",candidates:["Published AI-assisted proof claims"],families:["Clay Mathematics Institute problem and rules registries","mathematics literature"],conclusion:"No Clay-recognized problem solution primarily produced by AI was identified; absence is not numeric zero.",limitations:"Unpublished work cannot be screened."},
 "ai-exclusively-professors":{status:"no-verified-result",scope:"Accredited degree-granting AI universities.",candidates:["MBZUAI — human faculty directory disqualifies it"],families:["university faculty directories","accreditation records"],conclusion:"No qualifying all-AI professoriate was verified.",limitations:"Institutions without transparent staffing remain unverified."},
 "ai-led-companies":{status:"no-verified-result",scope:"Canonical top-100 public-company population and executive authority.",candidates:["NetDragon / Tang Yu — AI rotating CEO, company outside population"],families:["company filings","official executive announcements","public-company rankings"],conclusion:"No qualifying top-100 company was verified as primarily AI-managed.",limitations:"Private internal delegation is not observable."},
 "ai-led-countries-1":{status:"no-verified-result",scope:"195 sovereign states and primary national executive authority.",candidates:["Albania / Diella — cabinet role; human Prime Minister retains authority"],families:["government rosters","constitutional and parliamentary sources"],conclusion:"No sovereign state was verified as AI-led.",limitations:"Informal use of decision systems is not fully public."},
 "robotics-2":{status:"unknown",scope:"Worldwide ordinary households with qualifying general-purpose humanoids.",candidates:["manufacturer-controlled R&D household placements","preorders and delivery announcements"],families:["manufacturer deployment reports","household surveys"],conclusion:"No compatible worldwide household numerator and denominator support a percentage.",limitations:"Private placements and inactive units are incompletely disclosed."},
 "robotics-police-countries":{status:"no-verified-result",scope:"Sovereign states granting robots independent lawful detention authority.",candidates:["Singapore patrol and engagement robots — support role only"],families:["police operational rules","statutes","official deployments"],conclusion:"No qualifying independent detention authority was verified.",limitations:"Local operating policies may not be published."},
 "robotics-3":{status:"unknown",scope:"Worldwide major surgeries and fully autonomous qualifying operations.",candidates:["autonomous subtasks","preclinical systems"],families:["surgical registries","regulators","peer-reviewed trials"],conclusion:"No compatible worldwide numerator/denominator exists.",limitations:"Procedure autonomy is inconsistently classified."},
 "self-driving-car-2":{status:"lower-bound",scope:"Ordinary driverless L4/L5 passenger service by sovereign state.",candidates:["United States","China","United Arab Emirates","Japan"],families:["transport regulators","municipal deployment permits"],conclusion:"Four separately documented countries establish a conservative floor.",limitations:"The search is systematic but not a worldwide exhaustive registry."},
 "self-driving-car-3":{status:"no-verified-result",scope:"195 states with nationwide unrestricted Level 5 service.",candidates:["geofenced and ODD-limited L4 deployments"],families:["national transport regulators","deployment permits"],conclusion:"No nationwide unrestricted Level 5 deployment was verified.",limitations:"Rapid permit changes require quarterly review."},
 "self-driving-car-1":{status:"no-verified-result",scope:"Global road distance driven at SAE Level 5.",candidates:["geofenced Level 4 fleets"],families:["national distance statistics","SAE automation reports"],conclusion:"No compatible verified Level-5 global distance share was found.",limitations:"Global distance reporting is fragmented."},
 "self-driving-car-4":{status:"no-verified-result",scope:"Ordinary-use active cars satisfying unrestricted SAE Level 5.",candidates:["consumer Level 2 systems","geofenced Level 4 robotaxis"],families:["type approvals","manufacturer specifications"],conclusion:"No qualifying ordinary-use Level 5 car was verified.",limitations:"Prototype inventories are not comprehensive."},
 "superconductor-1":{status:"no-verified-result",scope:"Independently replicated ambient-pressure superconductivity records.",candidates:["retracted or unreplicated high-temperature claims"],families:["peer-reviewed replication literature","materials databases"],conclusion:"No qualifying ambient-pressure result was verified.",limitations:"New laboratory claims may precede replication."},
 "bci-2":{status:"lower-bound",scope:"Formal industry-sponsored chronic neural-reading BCI trial authorizations.",candidates:["United States","United Kingdom","UAE","Canada","Australia","China","Japan","Switzerland"],families:["trial registries","regulators","sponsor trial notices"],conclusion:"Eight jurisdictions are retained as a documented floor, not an exhaustive total.",limitations:"Authorization systems and public detail differ by country."},
 "bci-3":{status:"verified",scope:"Sovereign states with ordinary market approval for an invasive neural-reading BCI medical device.",candidates:["China / NEO approval","subsequent approvals through cutoff"],families:["NMPA and national regulator releases","international regulator databases"],conclusion:"China is the sole qualifying country at the cutoff.",limitations:"Approval terminology was screened conservatively.",complete:"systematic-nonexhaustive"},
 "bci-4":{status:"no-verified-result",scope:"Countries with ordinary consumer availability of qualifying internal BCIs.",candidates:["clinical trials","China's indication-specific NEO medical approval"],families:["medical-device regulators","commercial catalogues"],conclusion:"No unrestricted ordinary-consumer availability was verified.",limitations:"Medical prescription availability is not consumer availability."},
 "mind-upload-price-1":{status:"not-applicable",scope:"Commercial whole-person mind-upload services.",candidates:["connectomics services","brain emulation research"],families:["commercial catalogues","connectomics literature"],conclusion:"No defined commercial product exists, so a market price is not applicable.",limitations:"The status changes if a qualifying service launches.",complete:"targeted"},
 "mind-upload-adoption-1":{status:"no-verified-result",scope:"Unique persons qualifying as operational mind uploads.",candidates:["digital avatars","connectome reconstructions"],families:["neuroscience literature","commercial announcements"],conclusion:"No qualifying uploaded individual was verified.",limitations:"The construct requires functional evidence unavailable in present systems."},
 "mind-upload-adoption-2":{status:"no-verified-result",scope:"Sovereign states containing a qualifying uploaded person.",candidates:["digital-avatar projects","whole-brain simulation projects"],families:["national research programs","neuroscience literature"],conclusion:"No country qualifies because no qualifying individual was verified.",limitations:"Dependent on the person-level construct."},
 "vr-5":{status:"unknown",scope:"Worldwide unique people using immersive VR within one aligned 24-hour period.",candidates:["device installations","Steam sessions","platform MAU","social-VR users"],families:["platform disclosures","device telemetry","market studies"],conclusion:"Public metrics cannot be deduplicated, VR-filtered, and date-aligned into compatible DAU.",limitations:"A future estimate needs platform inputs, deduplication, VR-only filtering, alignment, and uncertainty."},
 "vr-4":{status:"no-verified-result",scope:"Simultaneous direct CNS replication of seven specified modalities.",candidates:["cortical visual prostheses","cortical tactile stimulation"],families:["neuroprosthetics trials","peer-reviewed stimulation studies"],conclusion:"Limited artificial percepts exist, but no system replicates all seven modalities simultaneously.",limitations:"The seven-modality set is an FPB convention."},
 "cultured-meat-1":{status:"unknown",scope:"Compatible annual worldwide cultivated-meat sales value share.",candidates:["approvals","tastings","private sales claims"],families:["market statistics","company filings","food regulators"],conclusion:"No compatible worldwide numerator and denominator were available.",limitations:"Private sales and inconsistent product scopes prevent calculation."},
 "cultured-meat-2":{status:"lower-bound",scope:"Sovereign countries with operative human-food authorization.",candidates:["Singapore","United States","Australia","New Zealand","Israel"],families:["national food regulators"],conclusion:"Five countries are individually supported as a conservative floor.",limitations:"Approval and sale are distinct; regulatory changes require review."},
 "cultured-meat-4":{status:"no-verified-result",scope:"Sovereign states with a comprehensive statutory ban on all cultivated meat.",candidates:["subnational restrictions","narrow product restrictions"],families:["national legislation","food regulator notices"],conclusion:"No qualifying comprehensive sovereign-state ban was verified.",limitations:"Fast-moving legislation and translations limit exhaustiveness."},
 "space-mars-pop":{status:"zero",scope:"Complete historical record of human spaceflight destinations.",candidates:["All crewed missions","Mars mission records"],families:["NASA mission archives","international human-spaceflight histories"],conclusion:"No human has reached Mars; the current Mars human population is exactly zero.",limitations:"Event-driven review is required after any crewed Mars mission.",complete:"exhaustive"},
 "fusion-1":{status:"zero",scope:"Operating grid-connected commercial fusion plants worldwide.",candidates:["experimental fusion facilities","planned pilot plants"],families:["DOE fusion roadmap","energy regulators","facility registries"],conclusion:"No operating grid-connected commercial fusion plant exists at the cutoff.",limitations:"Event-driven review is required.",complete:"exhaustive"},
 "fusion-2":{status:"zero",scope:"Global electricity generated by qualifying commercial fusion plants.",candidates:["experimental fusion output"],families:["global electricity statistics","fusion facility registries"],conclusion:"With no qualifying plant, commercial fusion generation and its share are exactly zero.",limitations:"Linked to fusion-1's plant boundary.",complete:"exhaustive"},
 "fusion-3":{status:"zero",scope:"Historical magnetic-confinement devices maintaining Q_plasma > 1 continuously.",candidates:["JET Q≈0.67","NIF target gain — excluded boundary"],families:["ITER historical records","magnetic-confinement literature"],conclusion:"ITER states Q=1 has never been reached in magnetic confinement; qualifying duration is zero hours.",limitations:"This does not describe inertial target gain.",complete:"exhaustive"},
 "fusion-4":{status:"zero",scope:"Actual positive net electrical export by any fusion facility.",candidates:["fusion heat","gross projections","scientific gain"],families:["facility records","energy regulators","DOE and ITER"],conclusion:"No fusion facility has exported positive net electricity.",limitations:"Event-driven review is required.",complete:"exhaustive"},
};

export const RESEARCH_AUDITS: readonly ResearchAuditRecord[] = Object.entries(descriptions).map(([measurementId,d])=>({id:`audit-${measurementId}-2026-08-16`,measurementId,researchCutoff:cutoff,performedAt:cutoff,methodVersion:"FPB-research-audit-1.0",completeness:d.complete??"systematic-nonexhaustive",searchScope:d.scope,candidateClassesChecked:d.candidates,registriesOrSourceFamiliesChecked:d.families,sourceIdsReviewed:[],candidatesReviewed:d.candidates,nearMissesReviewed:d.candidates,conclusion:d.conclusion,limitations:d.limitations,supportsStatus:d.status}));
export const researchAuditFor=(measurementId:string)=>RESEARCH_AUDITS.find(a=>a.measurementId===measurementId);
