import { MAIN_DOMAINS, type Measurement } from "../components/progress-table-data.ts";
import { RETIRED_MEASUREMENTS } from "../components/retired-measurements.ts";
import { DATASET_SNAPSHOT } from "../data/dataset-snapshot.ts";
import { getCatalogueCounts, getCompletedLevelCount, getGlobalProgress } from "./progress-utils.ts";
import { RESEARCH_AUDITS, researchAuditFor } from "./research-audits.ts";

export const ACTIVE_MEASUREMENTS = MAIN_DOMAINS.flatMap(domain => domain.subdomains.flatMap(field => field.measurements.map(measurement => ({ measurement, domain: domain.name, field: field.name }))));
const cadenceDays = { continuous: 7, monthly: 31, quarterly: 92, annual: 366, "event-driven": 366, legacy: 366 } as const;
export function freshness(measurement: Measurement, asOf = DATASET_SNAPSHOT.researchCutoff) {
  const due = new Date(`${measurement.researchCutoff}T00:00:00Z`); due.setUTCDate(due.getUTCDate() + cadenceDays[measurement.protocol.updateCadence]);
  return { state: new Date(`${asOf}T00:00:00Z`) > due ? "stale" as const : "fresh" as const, nextReviewDue: due.toISOString().slice(0, 10) };
}
export function qualitySignals(measurement: Measurement) {
  const signals: { severity: "ERROR" | "WARNING" | "INFO"; code: string; message: string }[] = [];
  if (freshness(measurement).state === "stale") signals.push({ severity: "WARNING", code: "stale", message: "Review is overdue for this cadence." });
  if (!measurement.evidence.length) signals.push(researchAuditFor(measurement.id)?{ severity: "INFO", code: "research-audit-only", message: "No direct external evidence is linked; a public research audit supports this conclusion." }:{ severity: "WARNING", code: "missing-evidence", message: measurement.observation.evidenceException?.explanation ?? "No evidence is linked." });
  if (measurement.evidence.some(e => !e.publicationDate)) signals.push({ severity: "INFO", code: "missing-publication-date", message: "At least one source has no recorded publication date." });
  if (measurement.valueStatus === "estimate" && !measurement.observation.uncertainty) signals.push({ severity: "WARNING", code: "estimate-without-range", message: "Estimate has no structured uncertainty range." });
  if (measurement.valueStatus === "lower-bound" && !(measurement.observation.qualifyingEntities?.length)) signals.push({ severity: "INFO", code: "incomplete-enumeration", message: "Lower bound has no complete structured enumeration." });
  if (measurement.valueStatus === "zero") signals.push({ severity: "INFO", code: "zero-review", message: "ZERO basis must be reassessed at every cutoff." });
  if (measurement.definitionHistory.some(h => h.effectiveFrom === DATASET_SNAPSHOT.researchCutoff)) signals.push({ severity: "INFO", code: "definition-recently-changed", message: "Definition changed in this snapshot." });
  return signals;
}
export function compactRecord(measurement: Measurement) {
  const location = ACTIVE_MEASUREMENTS.find(x => x.measurement.id === measurement.id)!; const fresh = freshness(measurement);
  const researchAudit=researchAuditFor(measurement.id); return { id: measurement.id, title: measurement.title, question: measurement.question, domain: location.domain, field: location.field, definitionVersion: measurement.definitionVersion, construct: measurement.construct, temporalType: measurement.temporalType, indicatorType: measurement.indicatorType, unit: measurement.unit, researchCutoff: measurement.researchCutoff, updateCadence: measurement.protocol.updateCadence, currentValue: measurement.currentValue ?? null, status: measurement.valueStatus, displayValue: measurement.displayValue ?? null, freshness: fresh.state, nextReviewDue: fresh.nextReviewDue, evidenceCount: measurement.evidence.length, researchAuditId:researchAudit?.id??null, supportComplete:Boolean(measurement.evidence.length||researchAudit||measurement.valueStatus==="not-applicable"), fullSpecUrl: `/research/${measurement.id}` };
}
export function fullRecord(measurement: Measurement) { return { snapshot: DATASET_SNAPSHOT, specification: { ...measurement, observation: undefined, levels: undefined, evidence: undefined, forecasts: undefined, history: undefined, observationHistory: undefined, definitionHistory: undefined }, currentObservation: measurement.observation, researchProtocol: measurement.protocol, qualificationCriteria: measurement.qualification, evidence: measurement.evidence, researchAudit:researchAuditFor(measurement.id)??null, entities: measurement.observation.qualifyingEntities ?? [], cohorts:measurement.observation.qualifyingCohorts??[], nearMisses: measurement.observation.nearMisses ?? [], ladder: { ...measurement.ladder, levels: measurement.levels }, forecasts: measurement.forecasts, history: { observations: measurement.observationHistory, definitions: measurement.definitionHistory }, warnings: qualitySignals(measurement) }; }
export function updateManifest() { return { schemaVersion: "FPB-update-manifest-2.0", snapshot: DATASET_SNAPSHOT, workflow:["ChatGPT retrieves this manifest and researches newer evidence","ChatGPT returns an FPB-update-proposal","Human reviews","Codex applies the approved proposal","History, snapshot, and support metadata update","Validation, tests, and build run"], generatedFrom: "canonical FPB-MS dataset", measurements: ACTIVE_MEASUREMENTS.map(({ measurement }) => { const compact = compactRecord(measurement); const audit=researchAuditFor(measurement.id); return { id: measurement.id, question: measurement.question, definitionVersion: measurement.definitionVersion, temporalType: measurement.temporalType, currentAnswer: { value: measurement.currentValue ?? null, displayValue: measurement.displayValue ?? null, status: measurement.valueStatus }, lastResearchCutoff: measurement.researchCutoff, updateCadence: measurement.protocol.updateCadence, nextReviewDue: compact.nextReviewDue, freshness: compact.freshness, preferredSources: measurement.protocol.preferredSourceTypes, directEvidenceIds:measurement.evidence.map(e=>e.id), latestResearchAuditId:audit?.id??null, uncertaintyNotes: measurement.observation.uncertainty?.note ?? measurement.observation.methodNote ?? null, qualifyingEntities: measurement.observation.qualifyingEntities ?? [], qualifyingCohorts:measurement.observation.qualifyingCohorts??[], nearMisses:measurement.observation.nearMisses??[], unresolvedWarnings:qualitySignals(measurement).map(x=>x.message), fullSpecUrl: compact.fullSpecUrl }; }) }; }
export function auditSummary() { const counts = getCatalogueCounts(MAIN_DOMAINS), progress = getGlobalProgress(MAIN_DOMAINS), measurements = ACTIVE_MEASUREMENTS.map(x => x.measurement); const statuses = Object.fromEntries([...new Set(measurements.map(m => m.valueStatus))].map(s => [s, measurements.filter(m => m.valueStatus === s).length])); const supported=measurements.filter(m=>m.evidence.length||researchAuditFor(m.id)||m.valueStatus==="not-applicable").length; return { standardVersion: DATASET_SNAPSHOT.standardVersion, snapshotId: DATASET_SNAPSHOT.id, globalResearchCutoff: DATASET_SNAPSHOT.researchCutoff, ...counts, retiredMeasurements: RETIRED_MEASUREMENTS.length, score: progress, statuses, evidenceCoverage: { withEvidence: measurements.filter(m => m.evidence.length).length, uniqueSources:new Set(measurements.flatMap(m=>m.evidence.map(e=>e.id))).size, total: measurements.length }, researchAuditCoverage:{withAudit:RESEARCH_AUDITS.length,total:measurements.length}, supportCoverage:{complete:supported,total:measurements.length}, specificationCompleteness: measurements.filter(m => m.rationale && m.protocol.researchProcedure).length, ladderRationaleCompleteness: measurements.filter(m => m.levels.every(l => l.rationale)).length, fresh: measurements.filter(m => freshness(m).state === "fresh").length, stale: measurements.filter(m => freshness(m).state === "stale").length, warnings: measurements.reduce((n,m) => n + qualitySignals(m).filter(s => s.severity !== "INFO").length, 0) }; }
export function changelog() { return { observations: ACTIVE_MEASUREMENTS.flatMap(({measurement}) => measurement.observationHistory.map(h => ({...h, title: measurement.title}))), definitions: ACTIVE_MEASUREMENTS.flatMap(({measurement}) => measurement.definitionHistory.map(h => ({...h, title: measurement.title}))) }; }
export function findMeasurement(id: string) { return ACTIVE_MEASUREMENTS.find(x => x.measurement.id === id)?.measurement; }
export function currentLevel(m: Measurement) { return getCompletedLevelCount(m); }
