import type { Metadata } from "next";
import Link from "next/link";
import { MAIN_DOMAINS } from "@/components/progress-table-data";
import { DOMAIN_ID_TO_SLUG } from "@/lib/site";

export const metadata: Metadata = { title: "Research specification", description: "The canonical catalogue of all 48 Future Progress Bar research questions, definitions and result metadata.", alternates: { canonical: "/research" } };
export default function ResearchPage() { return <main className="research-page editorial-page"><header className="research-hero"><p className="atlas-kicker">How do we measure it?</p><h1>Research specification</h1><p>The website-native catalogue of the 48 active questions. This page and the live dashboard are generated from the same canonical definitions—never a copied question list.</p><div className="protocol"><h2>Global Measurement Protocol</h2><p>Results use the exact operational definition attached to each question. Current and record indicators remain distinct; incompatible denominators are not averaged; UNKNOWN, N/A and NO VERIFIED RESULT remain nonnumeric; and only L1–L7 contribute to the 336-milestone index.</p><Link href="/methodology">Read the philosophy, evidence hierarchy and scoring method →</Link></div></header>
  <nav className="research-toc" aria-label="Research specification contents"><strong>Contents</strong>{MAIN_DOMAINS.map(domain => <div key={domain.id}><a href={`#${domain.id}`}>{domain.name}</a>{domain.subdomains.map(sub => <a key={sub.id} href={`#${sub.id}`}>{sub.name}</a>)}</div>)}</nav>
  <section className="result-state-note"><h2>Result states</h2><p><strong>VERIFIED, ESTIMATE, LOWER BOUND, and VERIFIED ZERO</strong> are numeric observations with explicit epistemic meaning. <strong>UNKNOWN, N/A, and NO VERIFIED RESULT</strong> are not zero and cannot complete a threshold.</p></section>
  {MAIN_DOMAINS.map(domain => <section className="research-domain" id={domain.id} key={domain.id}><p className="atlas-kicker">Domain</p><h2>{domain.name}</h2>{domain.subdomains.map(sub => <section id={sub.id} className="research-subdomain" key={sub.id}><header><div><h3>{sub.name}</h3><p>{sub.description}</p></div><Link href={`/progress/${DOMAIN_ID_TO_SLUG[sub.id]}`}>View live progress →</Link></header><ol>{sub.measurements.map((m, index) => <li id={m.id} key={m.id}><div className="question-number">{String(index + 1).padStart(2, "0")}</div><article><p className="atlas-kicker">{m.id}</p><h4>{m.title}</h4><p className="research-question">{m.question}</p><details><summary>Operational definition &amp; metadata</summary><p>{m.definition}</p><dl><div><dt>Temporal type</dt><dd>{m.temporalType}</dd></div><div><dt>Indicator type</dt><dd>{m.indicatorType}</dd></div><div><dt>Unit</dt><dd>{m.unit}</dd></div>{m.denominator && <div><dt>Denominator</dt><dd>{m.denominator.description}{m.denominator.period ? ` · ${m.denominator.period}` : ""}</dd></div>}<div><dt>Research cutoff</dt><dd>{m.researchCutoff}</dd></div><div><dt>Current state</dt><dd>{(m.valueStatus ?? "verified").replaceAll("-", " ").toUpperCase()}</dd></div></dl></details></article></li>)}</ol></section>)}</section>)}
  <footer className="research-footer"><p>48 active questions · 12 fields · 5 domains · 336 scored L1–L7 milestones.</p><Link href="/archive">View the retired methodology archive →</Link></footer></main>; }
