import Link from "next/link";
import { notFound } from "next/navigation";
import { ACTIVE_MEASUREMENTS, currentLevel, findMeasurement, freshness, qualitySignals } from "@/lib/transparency";
import { FPB_GLOSSARY } from "@/lib/fpb-measurement-standard";
import { LEVEL_NAMES } from "@/lib/progress-utils";
import { DefinitionVersionBadge, DisclosurePanel, EvidenceBadge, FreshnessBadge, StatusBadge } from "@/components/ui";
export const dynamicParams=false;
export function generateStaticParams(){return ACTIVE_MEASUREMENTS.map(x=>({id:x.measurement.id}))}
export default async function MeasurementPage({params}:{params:Promise<{id:string}>}){
 const m=findMeasurement((await params).id); if(!m)notFound(); const location=ACTIVE_MEASUREMENTS.find(x=>x.measurement.id===m.id)!; const fresh=freshness(m), achieved=currentLevel(m); const answer=m.displayValue??m.currentValue??m.valueStatus;
 const nav=["overview","method","evidence","milestones","history"];
 return <main className="spec-page wide-page"><nav className="breadcrumbs"><Link href="/research">Research atlas</Link><span>/</span><span>{m.id}</span></nav>
 <header className="spec-hero"><div><p className="eyebrow">Canonical measurement specification</p><h1>{m.title}</h1><p className="research-question">{m.question}</p><div className="badge-row"><StatusBadge status={m.valueStatus}/><FreshnessBadge state={fresh.state}/><EvidenceBadge count={m.evidence.length}/><DefinitionVersionBadge version={m.definitionVersion}/></div></div><aside><small>Current answer</small><strong>{String(answer)}</strong><span>{["unknown","no-verified-result","not-applicable"].includes(m.valueStatus)?"Unscored epistemic result":`L${achieved} · ${LEVEL_NAMES[achieved]}`}</span><p>{achieved<7?`Next: L${achieved+1} · ${LEVEL_NAMES[achieved+1]}`:"All levels reached"}</p></aside></header>
 <nav className="anchor-nav" aria-label="On this page">{nav.map(x=><a key={x} href={`#${x}`}>{x}</a>)}</nav>
 <div className="spec-layout"><article>
 <section id="overview"><p className="eyebrow">01 · Overview</p><h2>What this measurement means</h2><p className="lead-copy">{m.construct}</p><div className="fact-grid"><dl><dt>Variable</dt><dd>{m.variable}</dd></dl><dl><dt>Unit &amp; direction</dt><dd>{m.unit} · {m.isLowerBetter?"lower":"higher"} is progress</dd></dl><dl><dt>Indicator</dt><dd>{m.indicatorType}</dd></dl><dl><dt>Temporal type</dt><dd>{m.temporalType}</dd></dl><dl><dt>Scope</dt><dd>{m.scope.geographic??"Worldwide unless defined otherwise"}</dd></dl><dl><dt>Research cutoff</dt><dd>{m.researchCutoff}</dd></dl></div><h3>Why it exists</h3><p>{m.rationale}</p><div className="callout"><strong>Status interpretation</strong><p>{m.observation.methodNote??m.observation.answerSummary??"The canonical observation is supported by the evidence package and qualification rules below."}</p>{m.valueStatus==="lower-bound"&&<p>Evidence establishes at least this value, but not an exhaustive total.</p>}{["unknown","no-verified-result"].includes(m.valueStatus)&&<p>Available compatible evidence does not support a defensible numeric result. This is not zero.</p>}</div></section>
 <section id="method"><p className="eyebrow">02 · Method</p><h2>Qualification &amp; protocol</h2><DisclosurePanel title="What counts" open><ul>{m.qualification.inclusionCriteria.map(x=><li key={x}>{x}</li>)}</ul></DisclosurePanel><DisclosurePanel title="What does not count"><ul>{m.qualification.exclusionCriteria.map(x=><li key={x}>{x}</li>)}</ul></DisclosurePanel><DisclosurePanel title="Boundary rules"><ul>{m.qualification.boundaryRules.map(x=><li key={x}>{x}</li>)}</ul></DisclosurePanel><DisclosurePanel title="Research protocol"><p>{m.protocol.researchProcedure}</p><dl><dt>Preferred source hierarchy</dt><dd>{m.protocol.preferredSourceTypes.join(" → ")}</dd><dt>Conflicts</dt><dd>{m.protocol.sourceConflictRule}</dd><dt>ZERO rule</dt><dd>{m.protocol.zeroRule}</dd><dt>UNKNOWN rule</dt><dd>{m.protocol.unknownRule}</dd></dl></DisclosurePanel>{m.qualification.glossaryReferences.length>0&&<DisclosurePanel title="Shared glossary">{m.qualification.glossaryReferences.map(k=><p key={k}><strong>{k}</strong> — {FPB_GLOSSARY[k as keyof typeof FPB_GLOSSARY]}</p>)}</DisclosurePanel>}</section>
 <section id="evidence"><p className="eyebrow">03 · Evidence</p><h2>Evidence package</h2>{m.evidence.length?<div className="evidence-grid">{m.evidence.map(e=><article className="source-card" key={e.id}><span>{e.sourceType.replaceAll("-"," ")}</span><h3><a href={e.url}>{e.title} ↗</a></h3><p>{e.organization??"Organization not recorded"} · published {e.publicationDate??"not recorded"} · accessed {e.accessedDate}</p><strong>Claim supported</strong><p>{e.supports}</p></article>)}</div>:<div className="warning-banner"><strong>Explicit evidence exception</strong><p>{m.observation.evidenceException?.explanation}</p></div>}<DisclosurePanel title={`Qualifying entities (${m.observation.qualifyingEntities?.length??0})`}>{m.observation.qualifyingEntities?.length?<ul>{m.observation.qualifyingEntities.map(e=><li key={e.key}><strong>{e.name}</strong> — {e.qualificationSummary}</li>)}</ul>:<p>No structured entity list applies.</p>}</DisclosurePanel><DisclosurePanel title={`Near misses (${m.observation.nearMisses?.length??0})`}>{m.observation.nearMisses?.length?<ul>{m.observation.nearMisses.map(e=><li key={e.name}><strong>{e.name}</strong> — {e.exclusionReason}</li>)}</ul>:<p>No important near misses are recorded.</p>}</DisclosurePanel></section>
 <section id="milestones"><p className="eyebrow">04 · Milestones</p><h2>Stone → Antimatter ladder</h2><p>{m.ladder.pattern} — {m.ladder.rationale}</p><ol className="ladder-list">{m.levels.map(l=><li className={l.level<=achieved?"is-reached":l.level===achieved+1?"is-next":""} key={l.level}><span>L{l.level}</span><div><h3>{LEVEL_NAMES[l.level]} <small>{l.level<=achieved?"Reached":"Not reached"}</small></h3><strong>{l.label??(l.kind==="numeric"?`${l.operator} ${l.goal} ${m.unit}`:l.conditionKey)}</strong><p>{l.rationale}</p></div></li>)}</ol></section>
 <section id="history"><p className="eyebrow">05 · History</p><h2>Versioned record</h2><h3>Reality changed</h3><div className="history-timeline">{m.observationHistory.map((h,i)=><article key={i}><time>{h.researchCutoff}</time><strong>{String(h.value??h.valueStatus)}</strong><p>{h.reasonForRevision??h.note??h.details?.join(" ")??"Canonical observation record."}</p></article>)}</div><h3>Methodology changed</h3><div className="history-timeline history-timeline--definition">{m.definitionHistory.map(h=><article key={h.definitionVersion}><time>{h.effectiveFrom}</time><strong>Definition v{h.definitionVersion}</strong><p>{h.reason} {h.migrationNote}</p>{h.comparabilityBreak&&<span className="quality-signal quality-signal--warning">Series break</span>}</article>)}</div></section>
 </article><aside className="spec-rail"><div><small>Dataset location</small><strong>{location.domain}</strong><span>{location.field}</span></div><div><small>Identity</small><strong>{m.id}</strong><span>Effective {m.effectiveFrom}</span></div><div><small>Review</small><strong>{fresh.nextReviewDue}</strong><span>{m.protocol.updateCadence}</span></div><Link className="button" href={`/forecasts?measurement=${m.id}`}>View forecasts</Link>{qualitySignals(m).length>0&&<div><small>Quality signals</small>{qualitySignals(m).map(s=><span className="quality-signal" key={s.code}>{s.severity}: {s.code}</span>)}</div>}</aside></div></main>
}
