import Link from "next/link"; import { notFound } from "next/navigation"; import { ACTIVE_MEASUREMENTS, currentLevel, findMeasurement, freshness, qualitySignals } from "@/lib/transparency"; import { FPB_GLOSSARY } from "@/lib/fpb-measurement-standard"; import { LEVEL_NAMES } from "@/lib/progress-utils";
export const dynamicParams = false; export function generateStaticParams() { return ACTIVE_MEASUREMENTS.map(x => ({id:x.measurement.id})); }
export default async function MeasurementPage({params}:{params:Promise<{id:string}>}) { const m=findMeasurement((await params).id); if(!m) notFound(); const location=ACTIVE_MEASUREMENTS.find(x=>x.measurement.id===m.id)!; const fresh=freshness(m), achieved=currentLevel(m); return <main className="editorial-page spec-page"><nav className="breadcrumbs"><Link href="/research">Research registry</Link><span>/</span><span>{m.id}</span></nav><header><p className="atlas-kicker">Canonical measurement specification</p><h1>{m.title}</h1><p className="research-question">{m.question}</p><div className="spec-facts"><span>ID <strong>{m.id}</strong></span><span>{location.domain} / {location.field}</span><span>Definition v{m.definitionVersion}</span><span>Effective {m.effectiveFrom}</span></div></header>
<section><h2>Current answer</h2><p className="spec-answer">{m.displayValue ?? m.currentValue ?? m.valueStatus} <strong>{m.valueStatus.replaceAll("-"," ").toUpperCase()}</strong></p><p>Current milestone state: L{achieved} {LEVEL_NAMES[achieved]}; {achieved<7?`next is L${achieved+1} ${LEVEL_NAMES[achieved+1]}`:"all levels reached"}.</p></section>
<section><h2>Freshness</h2><dl><div><dt>Research cutoff</dt><dd>{m.researchCutoff}</dd></div><div><dt>Observation date</dt><dd>{m.observationDate??"Not separately applicable"}</dd></div><div><dt>Data period</dt><dd>{m.dataPeriod??"Point-in-time observation"}</dd></div><div><dt>Cadence</dt><dd>{m.protocol.updateCadence}</dd></div><div><dt>Status / next review</dt><dd>{fresh.state.toUpperCase()} · {fresh.nextReviewDue}</dd></div></dl></section>
<section><h2>What exactly is measured?</h2><p>{m.construct}</p><dl><div><dt>Variable</dt><dd>{m.variable}</dd></div><div><dt>Unit / direction</dt><dd>{m.unit} · {m.isLowerBetter?"lower":"higher"} is progress</dd></div><div><dt>Indicator / temporal</dt><dd>{m.indicatorType} · {m.temporalType}</dd></div><div><dt>Scope</dt><dd>{m.scope.geographic??"Worldwide unless the definition states otherwise"}</dd></div></dl><h3>Why this metric exists</h3><p>{m.rationale}</p></section>
<section><h2>Qualification boundaries</h2><h3>What counts?</h3><ul>{m.qualification.inclusionCriteria.map(x=><li key={x}>{x}</li>)}</ul><h3>What does not count?</h3><ul>{m.qualification.exclusionCriteria.map(x=><li key={x}>{x}</li>)}</ul><h3>Boundary rules</h3><ul>{m.qualification.boundaryRules.map(x=><li key={x}>{x}</li>)}</ul><h3>Shared glossary concepts</h3>{m.qualification.glossaryReferences.length?<dl>{m.qualification.glossaryReferences.map(k=><div key={k}><dt>{k}</dt><dd>{FPB_GLOSSARY[k as keyof typeof FPB_GLOSSARY]}</dd></div>)}</dl>:<p>No shared glossary concept supplements this metric-specific definition.</p>}</section>
<section><h2>Research protocol</h2><p>{m.protocol.researchProcedure}</p><dl><div><dt>Preferred hierarchy</dt><dd>{m.protocol.preferredSourceTypes.join(" → ")}</dd></div><div><dt>Conflicts</dt><dd>{m.protocol.sourceConflictRule}</dd></div><div><dt>Ties</dt><dd>{m.protocol.tieRule??"Apply all scope and compatibility rules; retain co-holders where the result is genuinely tied."}</dd></div><div><dt>ZERO</dt><dd>{m.protocol.zeroRule}</dd></div><div><dt>UNKNOWN</dt><dd>{m.protocol.unknownRule}</dd></div></dl></section>
<section><h2>Current observation reasoning</h2><p>{m.observation.methodNote??m.observation.answerSummary??"The displayed answer is the canonical observation supported by the linked evidence package and qualification rules."}</p>{m.observation.uncertainty&&<p>Uncertainty: {JSON.stringify(m.observation.uncertainty)}</p>}{m.observation.zeroBasis&&<p><strong>ZERO basis:</strong> {m.observation.zeroBasis}</p>}{m.valueStatus==="lower-bound"&&<p><strong>Why a lower bound:</strong> Evidence establishes at least this value but does not establish exhaustive enumeration.</p>}{["unknown","no-verified-result"].includes(m.valueStatus)&&<p><strong>Why nonnumeric:</strong> Available compatible evidence does not support a defensible verified number.</p>}</section>
<section><h2>Qualifying entities</h2>{m.observation.qualifyingEntities?.length?<ul>{m.observation.qualifyingEntities.map(e=><li key={e.key}><strong>{e.name}</strong> — {e.qualificationSummary}</li>)}</ul>:<p>No structured entity list applies or is currently recorded.</p>}<h2>Near misses</h2>{m.observation.nearMisses?.length?<ul>{m.observation.nearMisses.map(e=><li key={e.name}><strong>{e.name}</strong> — {e.exclusionReason}</li>)}</ul>:<p>No important near misses are currently recorded.</p>}</section>
<section><h2>Evidence</h2>{m.evidence.length?m.evidence.map(e=><article key={e.id}><h3><a href={e.url}>{e.title}</a></h3><p>{e.organization??"Organization not recorded"} · {e.sourceType} · published {e.publicationDate??"not recorded"} · accessed {e.accessedDate}</p><p><strong>Supported claim:</strong> {e.supports}</p></article>):<p><strong>Explicit evidence exception:</strong> {m.observation.evidenceException?.explanation}</p>}</section>
<section><h2>Full L1–L7 ladder</h2><p><strong>{m.ladder.pattern}</strong> — {m.ladder.rationale}</p><ol>{m.levels.map(l=><li key={l.level}><h3>L{l.level} {LEVEL_NAMES[l.level]} — {l.level<=achieved?"Reached":"Not reached"}</h3><p>{l.label??(l.kind==="numeric"?`${l.operator} ${l.goal} ${m.unit}`:l.conditionKey)}</p><p>{l.rationale}</p>{l.prerequisites?.length&&<p>Prerequisites: {l.prerequisites.join(", ")}</p>}</li>)}</ol></section>
<section><h2>Forecasts</h2><p>Forecasts are predictions, never observed evidence. <Link href={`/forecasts?measurement=${m.id}`}>View {m.forecasts.length} forecast records →</Link></p></section>
<section><h2>Observation history</h2>{m.observationHistory.map((h,i)=><article key={i}><strong>{h.researchCutoff}</strong><p>{h.value??h.valueStatus} — {h.reasonForRevision??h.note??h.details?.join(" ")??"Canonical observation record."}</p></article>)}</section><section className="definition-history"><h2>Definition history</h2>{m.definitionHistory.map(h=><article key={h.definitionVersion}><strong>{h.effectiveFrom} · v{h.definitionVersion}</strong><p>{h.reason} {h.migrationNote}</p>{h.comparabilityBreak&&<p><strong>Series/comparability break.</strong></p>}</article>)}</section><section><h2>Quality signals</h2>{qualitySignals(m).length?<ul>{qualitySignals(m).map(s=><li key={s.code}><strong>{s.severity}: {s.code}</strong> — {s.message}</li>)}</ul>:<p>Complete: no derived quality warnings.</p>}</section></main> }
