import type { Metadata } from "next"; import Link from "next/link"; import { EditorialPage } from "@/components/editorial-page";
export const metadata:Metadata={title:"About",description:"Why Future Progress Bar maps technological capability, adoption and civilization-scale change from Stone to Antimatter.",alternates:{canonical:"/about"}};
export default function AboutPage(){return <EditorialPage eyebrow="About the project" title="A field guide to technological change" intro="Future Progress Bar is an independent interactive data project: part dashboard, part speculative atlas, and part record of how difficult claims about the future are defined.">
<section><h2>Why it exists</h2><p>Technological progress is often discussed through isolated announcements. A benchmark rises, a prototype launches, or a forecast moves, but it remains difficult to see how these events relate to adoption, institutions and long-term human outcomes. Future Progress Bar puts selected indicators into a common milestone language so readers can inspect both movement and distance.</p><p>The project is meant to encourage questions rather than manufacture certainty. What would count as meaningful progress? Is a capability repeatable? Has it left the laboratory? Is the underlying value known at all?</p></section>
<section><h2>What the atlas measures</h2><p>Five main domains organize the atlas: <strong>Automation</strong> covers AI, robotics and autonomous vehicles; <strong>Civilization</strong> follows longevity and space exploration; <strong>Hardware</strong> covers quantum computing and superconductors; <strong>Neuro</strong> follows brain–computer interfaces, mind uploading and virtual reality; and <strong>Sustainability</strong> covers cultivated meat and fusion energy.</p><p>Within those domains, 12 subdomains each contribute four active measurements and a North Star graph. The 48 measurements combine technological capability, deployment and adoption, societal transformation, policy or market access, and long-run civilization indicators. The mix is intentional: laboratory performance alone cannot describe whether a technology changes life at scale.</p></section>
<section><h2>Stone → Antimatter</h2><p>Every active measurement has seven thresholds. Stone is the visible Level 0 baseline and does not score. The seven scored thresholds run from Level 1 Iron through Copper, Bronze, Silver, Gold and Platinum to Level 7 Antimatter. The names create a readable journey through unlike fields; they are this project’s milestone framework, not established scientific categories.</p><p>North Stars play a different role. Their graphs show a long-run frontier or contextual trend for a subdomain, but they do not add an eighth measurement. The global civilization score counts achieved measurement thresholds across the active catalogue. It is a project-defined comparative index—not an objective scientific percentage of humanity’s completion or a verdict on social progress.</p></section>
<section><h2>Why the far future is included</h2><p>Some milestones are deliberately speculative. They allow present capability, plausible extension and genuinely unknown territory to appear on one map. Mind uploading is the clearest example: dormant metrics are not presented as existing achievements. Far-future thresholds make assumptions visible and give forecasts something concrete to disagree about.</p></section>
<section><h2>A publication as well as a tool</h2><p>The graphs and progress bars are supported by definitions, epistemic labels, histories and explanatory field guides. Start with the <Link href="/methodology">methodology</Link>, review the <Link href="/sources">source approach</Link>, or open any subdomain from the progress atlas. Questions and corrections can use the genuine public channel on the <Link href="/contact">contact page</Link>.</p></section>
</EditorialPage>}
