import { EditorialPage } from "@/components/editorial-page"; import { FPB_GLOSSARY, FPB_MEASUREMENT_STANDARD } from "@/lib/fpb-measurement-standard"; import { StatusBadge } from "@/components/ui";
const sections=[
["scope","Scope & purpose","FPB-MS defines reproducible, inspectable progress measurements. It is a public internal standard, not external certification."],
["anatomy","Measurement anatomy","A measurement MUST separate its versioned specification, observation, evidence, ladder, histories, and forecasts."],
["questions","Question standard","A question MUST name one variable, scope, and temporal interpretation and MUST NOT silently change with the answer."],
["evidence","Evidence hierarchy",FPB_MEASUREMENT_STANDARD.evidenceHierarchy.join(" → ")+". Sources SHOULD support the exact claim; conflicts MUST be resolved by construct fit and authority, not by averaging incompatible values."],
["scoring","Milestones & scoring","Each active measurement has L1–L7 for one unchanged variable. Only reached observed levels score; forecasts and North Stars MUST NOT score."],
["versioning","Versioning","Definition changes MUST advance semantic definition versions and remain distinct from observation changes. Comparability breaks MUST be disclosed."],
] as const;
export default function StandardsPage(){return <EditorialPage eyebrow="Public technical standard" title={`FPB-MS ${FPB_MEASUREMENT_STANDARD.version}`} intro="The normative rules that keep every measurement reproducible, inspectable, and honest about uncertainty."><nav className="toc" aria-label="On this page"><strong>On this page</strong>{sections.map(([id,h])=><a href={`#${id}`} key={id}>{h}</a>)}<a href="#states">Epistemic states</a><a href="#temporal">Temporal types</a><a href="#glossary">Glossary</a></nav><section><div className="normative-grid"><div><strong>MUST</strong><p>Required for conformance.</p></div><div><strong>MUST NOT</strong><p>Prohibited by the standard.</p></div><div><strong>SHOULD</strong><p>Strong recommendation; document exceptions.</p></div><div><strong>MAY</strong><p>Optional implementation choice.</p></div></div></section>{sections.map(([id,h,p])=><section id={id} key={id}><p className="eyebrow">Normative rule</p><h2>{h}</h2><p>{p}</p></section>)}<section id="states"><p className="eyebrow">Reference</p><h2>Epistemic states</h2><div className="state-grid">{Object.entries(FPB_MEASUREMENT_STANDARD.epistemicStates).map(([k,v])=><article key={k}><StatusBadge status={k}/><p>{v}</p></article>)}</div><div className="comparison"><article><StatusBadge status="zero"/><h3>A verified quantity</h3><p>ZERO requires a logical, authoritative exhaustive, or documented exhaustive basis.</p></article><span aria-hidden="true">≠</span><article><StatusBadge status="unknown"/><h3>A limit of knowledge</h3><p>Absence of evidence must not become zero. UNKNOWN preserves unavailable numbers.</p></article></div></section><section id="temporal"><p className="eyebrow">Reference</p><h2>Temporal types</h2><div className="definition-grid">{Object.entries(FPB_MEASUREMENT_STANDARD.temporalTypes).map(([k,v])=><article key={k}><code>{k}</code><p>{v}</p></article>)}</div></section><section id="glossary"><p className="eyebrow">Shared language</p><h2>Glossary</h2><dl className="glossary-grid">{Object.entries(FPB_GLOSSARY).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section></EditorialPage>}
