import { PlaceholderTag, ProgressBar, ScorePair } from "@/components/ui";
import { getAspect, getHorseman, horsemen } from "@/data/world";
import { notFound } from "next/navigation";
import Link from "next/link";
export function generateStaticParams(){return horsemen.flatMap(h=>h.aspects.map(a=>({horseman:h.id,aspect:a.id})))}
export default async function AspectPage({params}:{params:Promise<{horseman:string;aspect:string}>}){const p=await params;const aspect=getAspect(p.horseman,p.aspect);const horseman=getHorseman(p.horseman);if(!aspect||!horseman)notFound();const max=Math.max(...aspect.historicalScores.map(x=>x.score??0),1);return <main className="aspect-page" style={{"--accent":horseman.accent} as React.CSSProperties}>
 <section className="aspect-hero"><Link href={`/${horseman.id}`} className="back">← BACK TO {horseman.name}</Link><div className="eyebrow">{horseman.name} / ASPECT DOSSIER</div><h1>{aspect.name}</h1><h2>{aspect.subtitle}</h2><p>{aspect.description}</p><PlaceholderTag/><ScorePair score={aspect.score}/><ProgressBar score={aspect.score}/></section>
 <div className="dossier-grid"><section className="panel history"><header><span className="eyebrow">DAMAGE HISTORY</span><h2>PROGRESS OVER TIME</h2></header><div className="chart" aria-label="Placeholder historical score chart">{aspect.historicalScores.map(point=><div className="chart-point" key={point.year}><span>{point.score?.toFixed(2)}</span><i style={{height:`${((point.score??0)/max)*100}%`}}/><small>{point.year}</small></div>)}</div><p className="warning">⚠ DEMO TIME SERIES — NOT FACTUAL HISTORICAL DATA</p></section>
 <section className="panel methodology"><header><span className="eyebrow">METHODOLOGY // {aspect.methodologyVersion}</span><h2>CALCULATION AUDIT</h2></header><div className="locked"><b>FORMULA PENDING</b><code>{aspect.formula.expression??"[ Deterministic expression not yet defined ]"}</code><p>{aspect.formula.explanation}</p></div><div className="table"><div className="tr th"><span>VARIABLE</span><span>RAW</span><span>NORMALIZED</span><span>WEIGHT</span><span>CONTRIBUTION</span></div>{aspect.formula.variables.map(v=><div className="tr" key={v.id}><span>{v.label}</span><span>—</span><span>—</span><span>—</span><span>—</span></div>)}</div><p className="warning">Every input will include its source, publication year, retrieval date, normalization, weight, and contribution.</p></section>
 <section className="panel phases"><header><span className="eyebrow">MILESTONES</span><h2>BOSS PHASES</h2></header>{aspect.milestones.map((m,i)=><div className="phase" key={m.id}><b>0{i+1}</b><span><small>{m.phase}</small>{m.title}</span><PlaceholderTag/></div>)}</section>
 <section className="panel sources"><header><span className="eyebrow">EVIDENCE CHAIN</span><h2>SOURCES</h2></header>{aspect.sources.map(s=><div className="source" key={s.id}><b>{s.title}</b><span>{s.organization}</span><p>{s.notes}</p><PlaceholderTag/></div>)}</section>
 <section className="panel weapons"><header><span className="eyebrow">HUMAN ARSENAL</span><h2>RELEVANT WEAPONS</h2></header>{aspect.technologies.map(t=><span className="weapon" key={t}>{t}</span>)}<p>Technologies may attack multiple aspects. They never become taxonomy layers.</p></section>
 <section className="panel update"><header><span className="eyebrow">CHANGE CONTROL</span><h2>UPDATE HISTORY</h2></header><p>No verified methodology releases yet.</p><dl><dt>VERSION</dt><dd>{aspect.methodologyVersion}</dd><dt>LAST UPDATED</dt><dd>{aspect.lastUpdated??"NOT YET CALCULATED"}</dd><dt>COMPARABILITY</dt><dd>PLACEHOLDER SERIES ONLY</dd></dl></section></div></main>}

