import type { Metadata } from "next";
import { EditorialPage } from "@/components/editorial-page";
export const metadata: Metadata = { title: "Methodology", description: "How Future Progress Bar defines measurements, milestone levels, North Stars, epistemic states, predictions and its global index.", alternates: { canonical: "/methodology" } };
const levels = [["Stone","Level 0: the pre-Iron baseline. It is visible but is not a scored milestone."],["Iron","Level 1 and the first scored threshold: a result that satisfies the measurement’s first goal."],["Copper","A developing capability with broader evidence or reach."],["Bronze","A material transition toward useful, sustained performance."],["Silver","An advanced milestone that moves the field beyond its present frontier."],["Gold","A mature and consequential form of the capability."],["Platinum","A near-horizon endpoint within the metric’s imagined progression."],["Antimatter","The seventh and most transformative measurement milestone; the global Antimatter era follows only after all active milestones are complete."]];
export default function MethodologyPage(){return <EditorialPage eyebrow="Editorial standard" title="How the atlas is built" intro="Future Progress Bar is a comparative milestone framework, not a scientific unit of civilization. Its purpose is to make definitions, uncertainty and long-range assumptions inspectable.">
  <section><h2>Measurements</h2><p>Each subdomain contains four active measurements. A measurement defines a phenomenon, a present value or explicit non-numeric state, a unit, and seven ordered thresholds. Some metrics reward higher values; others, such as cost, progress as the value falls. Capability, adoption, policy, market and outcome indicators are kept distinct where the data permits.</p><p>Completing a threshold counts as one milestone. The progress displayed inside a measurement interpolates between its baseline and the next threshold; it does not imply that the underlying phenomenon changes linearly.</p></section>
  <section><h2>Canonical Global Measurement Protocol</h2><p><strong>Time:</strong> current results use evidence valid at the recorded research cutoff; record results use the best qualifying historical result achieved by that cutoff. Currently deployed, implanted or active counts exclude retired, scrapped, permanently deactivated, explanted or deceased cases as appropriate. Annual series assign results to the year actually achieved or commercially available and never back-cast later capabilities, prices or permissions.</p><p><strong>Evidence:</strong> preference runs from regulators, national statistics agencies, standards and treaty or official record bodies, through peer-reviewed original research and major consortia, audited filings and official technical documentation, strong journalism linked to primary evidence, and finally transparent estimates. Retracted claims cannot establish records, and incompatible definitions are not averaged.</p><p><strong>Countries and shares:</strong> unless explicitly overridden, country metrics use 195 sovereign states: 193 UN members, the Holy See and the State of Palestine. Territories are not silently countries; separately governed jurisdictions may be reported separately. National authorization is not a hospital, ethics-board, municipal or pilot approval. Every share records a compatible denominator, geography and period.</p></section>
  <section><h2>Current values and updates</h2><p>Present-day results are checked against the metric’s definition and given a dated update. The project prefers a result that can be compared consistently over a more dramatic number that answers a different question. Definitions, qualifiers and method notes travel with the value. When complete evidence is unavailable, the display should say so rather than silently turning uncertainty into precision.</p></section>
  <section><h2>The Stone → Antimatter levels</h2><p>These names are Future Progress Bar’s own narrative milestone framework. They are not academic classifications or claims that history follows a fixed ladder.</p><dl className="level-list">{levels.map(([name,text])=><div key={name}><dt>{name}</dt><dd>{text}</dd></div>)}</dl></section>
  <section><h2>North Stars</h2><p>A North Star is the contextual graph for a subdomain. It follows a particularly legible long-run frontier or trajectory, while ordinary measurements determine the seven countable milestones. A North Star can illuminate direction without contributing an extra point to the global milestone total.</p></section>
  <section><h2>Epistemic states</h2><p>Numeric presentation should not erase the kind of knowledge behind a result.</p><dl><dt>VERIFIED</dt><dd>A result supported by evidence that meets the metric’s stated definition.</dd><dt>ESTIMATE</dt><dd>A best available approximation where a complete direct count is unavailable.</dd><dt>LOWER BOUND</dt><dd>At least this much is supported; the true value may be higher.</dd><dt>ZERO</dt><dd>A genuine measured or definition-based zero, eligible to be treated numerically.</dd><dt>UNKNOWN</dt><dd>The project does not have a defensible current result. <strong>UNKNOWN does not mean zero.</strong></dd><dt>N/A</dt><dd>The measurement does not meaningfully apply in the present situation.</dd><dt>NO VERIFIED RESULT</dt><dd>Claims or partial work may exist, but none yet satisfies the verification rule.</dd></dl></section>
  <section><h2>Predictions</h2><p>Forecast years attached to levels are outputs from the named AI models, captured as speculative forecasts rather than statements of fact or project endorsements. They should be compared, not averaged into certainty. Visitors can add personal forecasts; the current implementation stores those predictions in <code>localStorage</code> in that browser and does not create a Future Progress Bar account.</p></section>
  <section><h2>Retired metrics</h2><p>A living methodology sometimes discovers that a proxy is misleading, incomparable or superseded. Such metrics are archived with a reason and, where applicable, a replacement. Retirement preserves the audit trail instead of rewriting the project’s past silently.</p></section>
  <section><h2>The global index</h2><p>The global civilization score counts completed levels across all 48 active measurements. With seven levels per measurement, there are 336 measurement milestones. North Stars provide context but are not additional completed levels. The resulting Stone → Antimatter position is a project-defined comparative index—not an objective percentage of humanity’s completion, worth or destiny.</p></section>
  <section><h2>Corrections</h2><p>Definitions and data can be challenged through the public project-maintainer channel described on the <a href="/contact">contact page</a>. Corrections should preserve the distinction between updating evidence and changing a threshold.</p></section>
  </EditorialPage>}
