import Link from "next/link";
import { MainProgressBar } from "@/components/main-progress-bar";
import { MAIN_DOMAINS } from "@/components/progress-table-data";
import { getCompletedLevelCount } from "@/lib/progress-utils";
import { DOMAIN_ID_TO_SLUG, SITE_URL } from "@/lib/site";
import { AdSenseScript } from "@/components/adsense";
import { ACTIVE_MEASUREMENTS, auditSummary, changelog, currentLevel } from "@/lib/transparency";
import { DATASET_SNAPSHOT } from "@/data/dataset-snapshot";
import { EvidenceBadge, FreshnessBadge, SectionHeader, StatusBadge } from "@/components/ui";

export default function Home() {
  const audit=auditSummary(); const nearest=ACTIVE_MEASUREMENTS.filter(({measurement:m})=>currentLevel(m)===0&&typeof m.currentValue==="number").slice(0,4); const unknown=ACTIVE_MEASUREMENTS.filter(({measurement:m})=>["unknown","no-verified-result"].includes(m.valueStatus)); const recent=changelog().observations.slice().sort((a,b)=>b.researchCutoff.localeCompare(a.researchCutoff)).slice(0,4);
  const websiteData = { "@context": "https://schema.org", "@type": "WebSite", name: "Future Progress Bar", url: SITE_URL, description: "A living atlas of 48 measurements across humanity’s technological frontier." };
  return <main className="overview-page app-shell">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteData).replace(/</g, "\\u003c") }} />
    <section className="overview-hero"><p className="atlas-kicker">A living civilization atlas</p><h1>Technology’s long horizon, measured now.</h1><p>48 rigorous questions map humanity’s movement from Stone to Antimatter—without confusing evidence, uncertainty, or forecasts.</p><div><Link className="primary-cta" href="#fields">Explore the atlas</Link><Link href="/research">Search all measurements</Link></div><footer><span><small>Dataset snapshot</small><strong>{DATASET_SNAPSHOT.researchCutoff}</strong></span><span><small>Coverage</small><strong>12 fields · 5 domains</strong></span><span><small>Evidence</small><strong>{audit.evidenceCoverage.withEvidence}/{audit.evidenceCoverage.total} records</strong></span></footer></section>
    <MainProgressBar />
    <section className="home-signal-grid"><div><SectionHeader eyebrow="Next frontier" title="Closest to L1" intro="Numeric observations that have not yet crossed their first scored threshold."/><div className="compact-list">{nearest.map(({measurement:m,field})=><Link href={`/research/${m.id}`} key={m.id}><span><small>{field}</small><strong>{m.title}</strong></span><span>{m.displayValue??m.currentValue}<b>View →</b></span></Link>)}</div></div><div><SectionHeader eyebrow="Known unknowns" title={`${unknown.length} unresolved results`} intro="Unknown is an honest data state—not zero and not failure."/><div className="compact-list">{unknown.slice(0,4).map(({measurement:m})=><Link href={`/research/${m.id}`} key={m.id}><span><small>{m.id}</small><strong>{m.title}</strong></span><StatusBadge status={m.valueStatus}/></Link>)}</div></div></section>
    <section className="layer-guide" aria-labelledby="layer-heading"><div><p className="atlas-kicker">How to read this project</p><h2 id="layer-heading">Four layers, no blurred boundaries</h2></div><ol><li><strong>Where are we now?</strong><span>Observed results and scored milestones.</span></li><li><strong>How do we measure it?</strong><span>Questions, definitions and evidence.</span></li><li><strong>What happens next?</strong><span>AI and personal forecasts.</span></li><li><strong>Speculative horizon</strong><span>Atmosphere beyond measured reality.</span></li></ol></section>
    <section id="fields" className="field-atlas"><div className="section-heading"><p className="atlas-kicker">The complete atlas</p><h2>12 fields across five domains</h2><p>Each field contains exactly four active measurements and 28 possible scored milestones.</p></div>{MAIN_DOMAINS.map(domain => <section className={`domain-group domain-${domain.id}`} key={domain.id}><header><h3>{domain.name}</h3><span>{domain.subdomains.length} fields</span></header><div>{domain.subdomains.map(sub => { const achieved = sub.measurements.reduce((sum, m) => sum + getCompletedLevelCount(m), 0); return <Link className="field-card" href={`/progress/${DOMAIN_ID_TO_SLUG[sub.id]}`} key={sub.id}><span className="field-card__arrow" aria-hidden="true">↗</span><h4>{sub.name}</h4><p>{sub.description}</p><strong>{achieved} / 28 milestones</strong><div className="mini-progress" aria-label={`${achieved} of 28 milestones reached`}><i style={{ width: `${achieved / 28 * 100}%` }} /></div><small>Open four measurements</small></Link>; })}</div></section>)}</section>
    <section className="recent-section"><SectionHeader eyebrow="Dataset activity" title="Recent changes" intro="Observation updates describe reality or source data changing. Methodology changes remain separately versioned."/><div className="recent-grid">{recent.map((x,i)=><article key={`${x.measurementId}-${i}`}><time>{x.researchCutoff}</time><h3><Link href={`/research/${x.measurementId}`}>{x.title}</Link></h3><p>{x.reasonForRevision??x.note??"Canonical observation updated."}</p></article>)}</div><Link className="text-link" href="/changelog">Explore the full changelog →</Link></section>
    <section className="quality-strip"><div><p className="atlas-kicker">Data quality</p><h2>Transparent by design</h2><p>Every measurement carries a definition, evidence package, freshness state, and revision history.</p></div><div className="badge-row"><FreshnessBadge state="fresh"/><EvidenceBadge count={audit.evidenceCoverage.withEvidence}/><span className="badge badge--muted">{audit.specificationCompleteness}/48 complete specs</span></div><Link className="button" href="/audit">Open audit console</Link></section>
    <section className="next-steps"><div><p className="atlas-kicker">Go deeper</p><h2>Follow the evidence—or look ahead</h2></div><Link href="/research"><strong>Research specification</strong><span>All 48 canonical questions and definitions →</span></Link><Link href="/forecasts"><strong>Forecast desk</strong><span>Model scenarios and your predictions →</span></Link><Link href="/sources"><strong>Evidence ledger</strong><span>Sources supporting current results →</span></Link></section>
    <AdSenseScript />
  </main>;
}
