"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { EmptyState, EvidenceBadge, FreshnessBadge, StatusBadge } from "./ui";

export type AuditRow = { id:string; question:string; domain:string; field:string; answer:string; status:string; freshness:string; nextReviewDue:string; evidenceCount:number; definitionChanged:boolean; signals:{severity:string;code:string;message:string}[] };
export function AuditDashboard({ rows }: { rows: AuditRow[] }) {
  const [status,setStatus]=useState(""); const [domain,setDomain]=useState(""); const [fresh,setFresh]=useState(""); const [signal,setSignal]=useState(""); const [sort,setSort]=useState("id");
  const visible=useMemo(()=>rows.filter(r=>(!status||r.status===status)&&(!domain||r.domain===domain)&&(!fresh||r.freshness===fresh)&&(!signal||(signal==="warnings"?r.signals.some(s=>s.severity!=="INFO"):signal==="evidence"?r.evidenceCount===0:signal==="definition"?r.definitionChanged:signal==="zero"?r.status==="zero":r.status===signal))).sort((a,b)=>sort==="evidence"?a.evidenceCount-b.evidenceCount:sort==="freshness"?a.freshness.localeCompare(b.freshness):a[sort==="field"?"field":"id"].localeCompare(b[sort==="field"?"field":"id"])),[rows,status,domain,fresh,signal,sort]);
  const reset=()=>{setStatus("");setDomain("");setFresh("");setSignal("");};
  return <>
    <div className="signal-actions" aria-label="Quick quality filters"><button onClick={()=>setSignal("warnings")}>⚠ Warnings <strong>{rows.filter(r=>r.signals.some(s=>s.severity!=="INFO")).length}</strong></button><button onClick={()=>setSignal("evidence")}>▤ Missing evidence <strong>{rows.filter(r=>!r.evidenceCount).length}</strong></button><button onClick={()=>setSignal("definition")}>↺ Definition changed <strong>{rows.filter(r=>r.definitionChanged).length}</strong></button><button onClick={()=>setSignal("zero")}>0 ZERO review <strong>{rows.filter(r=>r.status==="zero").length}</strong></button></div>
    <div className="filter-bar" aria-label="Audit filters"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(rows.map(r=>r.status))].map(x=><option key={x}>{x}</option>)}</select></label><label>Freshness<select value={fresh} onChange={e=>setFresh(e.target.value)}><option value="">Fresh &amp; stale</option><option>fresh</option><option>stale</option></select></label><label>Domain<select value={domain} onChange={e=>setDomain(e.target.value)}><option value="">All domains</option>{[...new Set(rows.map(r=>r.domain))].map(x=><option key={x}>{x}</option>)}</select></label><label>Quality signal<select value={signal} onChange={e=>setSignal(e.target.value)}><option value="">All signals</option><option value="warnings">Warnings</option><option value="evidence">Evidence incomplete</option><option value="definition">Definition changed</option><option value="estimate">Estimates</option><option value="lower-bound">Lower bounds</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="id">Measurement ID</option><option value="field">Field</option><option value="evidence">Evidence count</option><option value="freshness">Freshness</option></select></label><button className="button button--quiet" onClick={reset}>Reset</button></div>
    <p className="result-count" aria-live="polite">Showing <strong>{visible.length}</strong> of {rows.length} measurements</p>
    {!visible.length?<EmptyState title="No measurements match"><button className="button" onClick={reset}>Clear filters</button></EmptyState>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Measurement</th><th>Current answer</th><th>Freshness</th><th>Evidence</th><th>Quality signals</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><th scope="row"><Link href={`/research/${r.id}`}><code>{r.id}</code><span>{r.question}</span></Link><small>{r.domain} · {r.field}</small></th><td><strong>{r.answer}</strong><StatusBadge status={r.status}/></td><td><FreshnessBadge state={r.freshness}/><small>Review {r.nextReviewDue}</small></td><td><EvidenceBadge count={r.evidenceCount}/></td><td>{r.signals.length?r.signals.map(s=><span className={`quality-signal quality-signal--${s.severity.toLowerCase()}`} title={s.message} key={s.code}>{s.severity}: {s.code}</span>):<span className="quality-ok">✓ Complete</span>}</td></tr>)}</tbody></table></div>}
  </>;
}
