"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { MAIN_DOMAINS } from "./progress-table-data";

type Saved = Record<string, { year: number; timestamp: number }>;
const allMeasurements = MAIN_DOMAINS.flatMap(d => d.subdomains.flatMap(s => s.measurements));
const rows = MAIN_DOMAINS.flatMap(domain => domain.subdomains.flatMap(subdomain => subdomain.measurements.flatMap(measurement => measurement.levels.flatMap(level => (level.aiPredictions ?? []).map(prediction => ({ ...prediction, type: "ai" as const, domain: domain.name, subdomain: subdomain.name, measurementId: measurement.id, title: measurement.title, level: level.level, threshold: level.label ?? `${level.goal.toLocaleString()} ${measurement.unit}` }))))));
const validKeys = new Set(MAIN_DOMAINS.flatMap(d => d.subdomains.flatMap(s => s.measurements.flatMap(m => m.levels.map(l => `${m.id}_${l.level}`)))));
export function ForecastsWorkspace() {
  const [saved, setSaved] = useState<Saved>({}); const [loaded, setLoaded] = useState(false); const [filter, setFilter] = useState<"both" | "ai" | "mine">("both"); const [query, setQuery] = useState(""); const [measurementId, setMeasurementId] = useState(MAIN_DOMAINS[0].subdomains[0].measurements[0].id); const [level, setLevel] = useState(1); const [year, setYear] = useState(2030);
  useEffect(() => { const timer = window.setTimeout(() => { try { const raw = JSON.parse(localStorage.getItem("userPredictions") ?? "{}") as Saved; const cleaned = Object.fromEntries(Object.entries(raw).filter(([key]) => validKeys.has(key))); localStorage.setItem("userPredictions", JSON.stringify(cleaned)); setSaved(cleaned); } catch { setSaved({}); } const requested = new URLSearchParams(window.location.search).get("measurement"); if (requested && allMeasurements.some(measurement => measurement.id === requested)) { setMeasurementId(requested); setQuery(requested); } setLoaded(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (loaded) localStorage.setItem("userPredictions", JSON.stringify(saved)); }, [saved, loaded]);
  const selected = allMeasurements.find(m => m.id === measurementId)!;
  const mine = Object.entries(saved).flatMap(([key, value]) => { const match = key.match(/^(.*)_(\d+)$/); if (!match) return []; const m = allMeasurements.find(item => item.id === match[1]); const l = m?.levels.find(item => item.level === Number(match[2])); return m && l ? [{ name: "My forecast", type: "mine" as const, measurementId: m.id, title: m.title, level: l.level, threshold: l.label ?? `${l.goal.toLocaleString()} ${m.unit}`, year: value.year, domain: "Personal", subdomain: "Saved in this browser" }] : []; });
  const visible = [...rows, ...mine].filter(r => (filter === "both" || r.type === filter) && `${r.title} ${r.name} ${r.subdomain}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.year - b.year);
  return <div className="forecast-workspace"><section className="forecast-controls" aria-label="Forecast controls"><div className="filter-group" role="group" aria-label="Forecast owner">{(["both", "ai", "mine"] as const).map(item => <button aria-pressed={filter === item} onClick={() => setFilter(item)} key={item}>{item === "both" ? "Both" : item === "ai" ? "AI models" : "Mine"}</button>)}</div><label>Search forecasts<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Measurement, field or model" /></label></section>
  <section className="prediction-editor"><div><p className="atlas-kicker">Personal forecast</p><h2>Add or update a prediction</h2><p>Stored only in this browser. Invalid or retired IDs are removed safely during migration.</p></div><form onSubmit={e => { e.preventDefault(); setSaved(current => ({ ...current, [`${measurementId}_${level}`]: { year, timestamp: Date.now() } })); }}><label>Measurement<select value={measurementId} onChange={e => { setMeasurementId(e.target.value); setLevel(1); }}>{allMeasurements.map(m => <option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label>Level<select value={level} onChange={e => setLevel(Number(e.target.value))}>{selected.levels.map(l => <option value={l.level} key={l.level}>L{l.level} — {l.label ?? `${l.goal} ${selected.unit}`}</option>)}</select></label><label>Year<input type="number" min="2026" max="9999" value={year} onChange={e => setYear(Number(e.target.value))} /></label><button type="submit">Save forecast</button></form></section>
  <section className="forecast-list"><div className="section-heading"><p className="atlas-kicker">What do we think happens next?</p><h2>{visible.length} forecast entries</h2><p>Forecast scenarios are visually and methodologically separate from observed results.</p></div>{Object.entries(visible.reduce<Record<string, typeof visible>>((groups, row) => { (groups[String(row.year)] ??= []).push(row); return groups; }, {})).map(([groupYear, items]) => <details open={Number(groupYear) <= 2030} key={groupYear}><summary>{groupYear}<span>{items?.length} entries</span></summary>{items?.map((r, i) => <article className={`forecast-row forecast-row--${r.type}`} key={`${r.measurementId}-${r.level}-${r.name}-${i}`}><div><span>{r.type === "ai" ? "AI MODEL FORECAST" : "PERSONAL FORECAST"}</span><h3>{r.title} · L{r.level}</h3><p>{r.threshold} · {r.name}</p></div><div><strong>{r.year}</strong>{r.type === "mine" && <button onClick={() => setSaved(current => { const next = { ...current }; delete next[`${r.measurementId}_${r.level}`]; return next; })}>Delete</button>}<Link href={`/research#${r.measurementId}`}>Definition</Link></div></article>)}</details>)}</section></div>;
}
