import type { Metadata } from "next"; import Link from "next/link";
import { EditorialPage } from "@/components/editorial-page"; import { MAIN_DOMAINS } from "@/components/progress-table-data"; import { DOMAIN_ID_TO_SLUG } from "@/lib/site";
export const metadata: Metadata={title:"Sources & data",description:"The evidence hierarchy, source limitations and measurement catalogue behind Future Progress Bar.",alternates:{canonical:"/sources"}};
export default function SourcesPage(){return <EditorialPage eyebrow="Data notes" title="Sources, evidence and coverage" intro="No single source type can answer every question in an atlas that ranges from population health to hypothetical mind emulation. Evidence is selected to fit each measurement, and gaps remain visible.">
<section><h2>Source hierarchy</h2><ol><li><strong>Official government and intergovernmental data</strong> for population, approvals, public programs and standardized reporting.</li><li><strong>Peer-reviewed literature</strong> for research results, definitions and independently scrutinized claims.</li><li><strong>Official company or institution technical material</strong> for systems whose primary performance data are released by their builders.</li><li><strong>Reputable secondary reporting</strong> where it adds verification, context or access to otherwise unavailable material.</li><li><strong>Explicit estimates</strong> where a complete primary global dataset does not exist.</li></ol><p>Higher placement is a preference, not an automatic guarantee of fitness. A current official dataset can still use a definition different from the one a measurement needs.</p></section>
<section><h2>What the catalogue currently stores</h2><p>The active data model includes definitions, present values and epistemic states, units, update dates, milestone thresholds, histories, forecast years and selected methodological notes. It does not yet contain a complete source-URL ledger for every historical point. This page therefore does not invent citations. Source metadata can be added progressively as individual records are audited.</p></section>
<section><h2>Measurement catalogue</h2><p>Use each field page to inspect its four active measurements, level definitions, history notes and North Star. The catalogue below is generated from the same active dataset as the dashboard.</p><div className="source-catalogue">{MAIN_DOMAINS.map(domain=><section key={domain.id}><h3>{domain.name}</h3>{domain.subdomains.map(sub=><div key={sub.id}><h4><Link href={`/progress/${DOMAIN_ID_TO_SLUG[sub.id]}`}>{sub.name}</Link></h4><ul>{sub.measurements.map(m=><li key={m.id}><span>{m.title}</span><small>{m.valueStatus?.replaceAll("-"," ") ?? "verified"} · updated {m.lastUpdated ?? "date not recorded"}</small></li>)}</ul></div>)}</section>)}</div></section>
<section><h2>Futuristic and incomplete data</h2><p>Some metrics describe technologies that do not yet exist, lack shared reporting standards or cannot have a complete global census. The appropriate result may be UNKNOWN, NO VERIFIED RESULT or an explicitly qualified estimate. Absence of a perfect dataset is not permission to convert speculation into a verified value.</p></section>
<section><h2>Using the data responsibly</h2><p>Read a value together with its unit, status, date and threshold definition. Comparisons across unrelated measurements are narrative comparisons inside this project framework, not scientific equivalences. For the counting rules, see the <Link href="/methodology">methodology</Link>.</p></section>
</EditorialPage>}
